Add workflow to update aur repo automatically
MaaAssistantArknights/maa-cli pull request #63
Opened 2023-10-04 13:16 UTC by horror-proton

This workflow would build and push new version number to `aur.archlinux.org/maa-cli.git` when a new tag was pushed.

Sed scripts were copied from [arch_package.yml](https://github.com/hykilpikonna/hyfetch/blob/master/.github/workflows/arch_package.yml)

2023-10-04 16:41 UTC, wangl-cc commented
Could you please consider adding this workflow to the release.yml file? It can be configured as a job with the condition:

```yml
if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
```

BTW, it appears that I currently lack permission to access the repository settings. Is there a way to grant me the access for this repository?

2023-10-05 03:26 UTC, horror-proton commented
I've set your repository role to admin, you should be able to access settings now

2023-10-05 04:09 UTC, horror-proton commented
I'm not sure, I guess it's fine to make it a separate workflow? 
Now it's a helper script to update PKGBUILD, and does not depend on any other part of release.yml. If arch-package fails, release.yml should not fail either. (that would be different if PKGBUILD is also included in this repo)
If something went wrong, arch-package can be disabled temporarily as a separate workflow until PKGBUILD is fixed.

2023-10-05 08:02 UTC, wangl-cc requested changes
I'm not familiar with publish AUR package, so I can not review details about job steps. But for step name, I prefer capitalise all words and "AUR" instead of "aur".

2023-10-05 08:02 UTC, wangl-cc commented on .github/workflows/arch-package.yml
> +name: arch-package
I prefer the name of this workflow is `Publish AUR Package`, and the filename can be `publish-aur.yml`.

2023-10-05 08:02 UTC, wangl-cc commented on .github/workflows/arch-package.yml
> +  push:
The trigger event can be 
```yml
on:
  release:
    types: [published]
  workflow_dispatch:
```
This workflow should be triggered by release and retry manually if failed. Maybe an input `pkgrel` is needed （or optional） for `workflow_dispatch`.

2023-10-05 08:02 UTC, wangl-cc commented on .github/workflows/arch-package.yml
> +  build:
I prefer the job id `publish` and name `Publish`.

2023-10-05 11:42 UTC, horror-proton commented on .github/workflows/arch-package.yml
> +  push:
It doesn't quite make sense to use a `pkgrel` which is not 1 in CI. `pkgver` is there for updating package without changing upstream version, usually when PKGBUILD was updated manually (or tag was force pushed?)

2023-10-05 12:04 UTC, wangl-cc approved these changes
LGTM. Feel free to squash and merge by yourslef when it's ready.

2023-10-05 14:18 UTC, merged